import { Volume2, Sparkles, Wifi, Battery, Radio, Zap, Usb, Lightbulb, Mic, Settings, Watch, Activity, Heart, Phone, Shield, Car, Gauge, Laptop } from "lucide-react";

export const altMap: Record<string, string> = {
  "Parlante Impetu":    "Parlante Bluetooth Mixor Ímpetu 20W RGB - Mayorista Argentina",
  "Parlante Latido":   "Parlante Portátil Mixor Latido Bluetooth 5.1 - Importador directo",
  "Parlante Curvas":   "Parlante Portátil Mixor Curvas LED RGB - Accesorios mayoristas Argentina",
  "Parlante Mio":      "Parlante Bluetooth Mixor Mío 5W con LED - Precio mayorista Argentina",
  "Parlante Leal":     "Parlante Bluetooth Mixor Leal 8W con Micrófono - Distribuidor mayorista",
  "Parlante Mito":     "Parlante Mixor Mito 8W con Perilla TWS - Mayorista tecnología Argentina",
  "Parlante Noche":    "Parlante de Fiesta Mixor Noche 30W Karaoke LED - Importador directo",
  "Parlante Caos":     "Parlante de Fiesta Mixor Caos 30W Karaoke RGB - Mayorista Argentina",
  "Parlante Alma":     "Parlante de Fiesta Mixor Alma 20W Doble Micrófono - Mayorista Argentina",
  "Parlante Recuerdo": "Parlante Portátil Mixor Recuerdo 5W Bluetooth RGB TWS - Mayorista Argentina",
  "Smartwatch Pulso":    "Smartwatch Mixor Pulso Pantalla LED 1.52'' - Mayorista Argentina",
  "Smartwatch Momentos": "Smartwatch Mixor Momentos ECG Llamadas Bluetooth - Importador directo",
  "Smartwatch Activo":   "Próximo Smartwatch Mixor Activo - Accesorios tecnológicos mayoristas",
  "TWS Claridad":         "Auriculares TWS Mixor Claridad Pantalla Táctil - Mayorista Argentina",
  "Auriculares Fusión":   "Auriculares Inalámbricos Mixor Fusión 6hs - Importador directo Argentina",
  "Auriculares Sensación":"Auriculares Inalámbricos Mixor Sensación 6hs - Distribuidor mayorista",
  "TWS Sincronia":        "Próximos Auriculares TWS Mixor Sincronía - Mayorista Argentina",
  "Cable Vinculo":    "Cable USB Tipo-C Mixor Vínculo 7.1A 1m - Mayorista Argentina",
  "Cable Impulso":    "Cable USB a Tipo-C Mixor Impulso 7.1A Carga Rápida - Importador directo",
  "Cable Vital":      "Cable USB Reforzado Mixor Vital 5.4A Cobre Puro - Mayorista Argentina",
  "Cable Eternidad":  "Próximo Cable Mixor Eternidad - Accesorios tecnológicos mayoristas",
  "Cable Pleno":      "Próximo Cable Mixor Pleno - Importador directo Argentina",
  "Cargador Leyenda":  "Cargador PD 65W Mixor Leyenda USB-C - Mayorista Argentina",
  "Cargador Somos":    "Cargador Rápido Mixor Somos 19W con Cable V8 - Importador directo",
  "Cargador Proton":   "Cargador Auto 12V Mixor Proton Doble USB - Mayorista Argentina",
  "Cargador Quiero":   "Cargador Pared Mixor Quiero 5.1A 2 USB con Cable Tipo-C - Mayorista",
  "Cargador Realidad": "Cargador 220V Mixor Realidad 4.4A Triple Protección - Mayorista Argentina",
  "Cargador Sinergia": "Próximo Cargador Mixor Sinergia - Accesorios tecnológicos mayoristas",
  "Inflador Ruta":   "Inflador Portátil Mixor Ruta 4000mAh Digital - Mayorista Argentina",
  "Holder Atrae":    "Soporte Magnético Mixor Atrae 360° Universal - Importador directo Argentina",
  "Cargador Nexo":   "Cargador Universal Notebook Mixor Nexo 9 Pines - Mayorista Argentina",
  "Micrófono Voz":   "Próximo Micrófono Mixor Voz - Accesorios tecnológicos mayoristas",
  "Lámpara Motivos": "Próxima Lámpara Mixor Motivos - Accesorios tecnológicos mayoristas",
  "Reloj Sueño":     "Próximo Reloj Mixor Sueño - Accesorios tecnológicos mayoristas",
};

export function getProductAlt(name: string): string {
  return altMap[name] ?? `Accesorios tecnológicos Mixor ${name} - Mayorista Argentina`;
}

export const categories = [
  { id: "parlantes", name: "Parlantes" },
  { id: "auriculares", name: "Auriculares" },
  { id: "smartwatch", name: "Smartwatch" },
  { id: "cables", name: "Cables" },
  { id: "cargadores", name: "Cargadores" },
  { id: "accesorios", name: "Accesorios" },
];

export const products = [
  {
    id: 1,
    name: "Parlante Impetu",
    category: "parlantes",
    price: "Consultar",
    code: "MODM-00EH",
    kit: "Kit x 40 unidades",
    image: "/images/parlante-bluetooth-mixor-impetu-20w-rgb-mayorista.webp",
    modalImage: "/images/parlante-bluetooth-mixor-impetu-modal-20w-rgb.webp",
    description: "Sonido estéreo 20W (10Wx2) con luces RGB y batería de 1800mAh",
    features: [
      { icon: Volume2, title: "Sonido Estéreo 20W", description: "Dos bocinas de 10W (10Wx2) que entregan bajos definidos y agudos claros." },
      { icon: Sparkles, title: "Atmósfera Visual", description: "Su panel frontal con luces RGB y controles gigantes ilumina tu entorno." },
      { icon: Wifi, title: "Conectividad Total", description: "Bluetooth, entrada USB, tarjeta TF o Radio FM integrada." },
      { icon: Battery, title: "Autonomía Confiable", description: "Batería de 1800mAh optimizada para uso constante." },
    ],
  },
  {
    id: 2,
    name: "Parlante Latido",
    category: "parlantes",
    price: "Consultar",
    code: "MODM-00C5",
    kit: "Kit x 50 unidades",
    image: "/images/parlante-portatil-mixor-latido-bluetooth-mayorista.webp",
    modalImage: "/images/parlante-portatil-mixor-latido-modal-bluetooth.webp",
    description: "Parlante inalámbrico portátil con Bluetooth 5.1 y batería de 800mAh",
    features: [
      { icon: Volume2, title: "Potencia de 8W", description: "Altavoz de 3'' con rango de respuesta de 80Hz - 20KHz para sonido nítido." },
      { icon: Wifi, title: "Bluetooth 5.1", description: "Conexión inalámbrica estable de última generación." },
      { icon: Battery, title: "Batería 800mAh", description: "Modelo 18650 con placa de protección IC integrada para uso prolongado." },
      { icon: Zap, title: "Portátil y Compacto", description: "Diseño de 3'' fácil de transportar. Lleva tu música a donde quieras." },
    ],
  },
  {
    id: 3,
    name: "Parlante Curvas",
    category: "parlantes",
    price: "Consultar",
    code: "MODM-000U",
    kit: "Kit x 50 unidades",
    image: "/images/parlante-portatil-mixor-curvas-led-rgb-mayorista.webp",
    modalImage: "/images/parlante-portatil-mixor-curvas-modal-led-rgb.webp",
    description: "Parlante portátil con luces LED RGB y diseño triangular compacto",
    features: [
      { icon: Volume2, title: "Potencia de 8W", description: "Altavoz de 3'' para sonido claro y portabilidad. Medidas: 14.6x14.6x6.9cm." },
      { icon: Lightbulb, title: "Luces LED RGB", description: "Iluminación LED multicolor que crea ambiente visual único." },
      { icon: Usb, title: "Conectividad Versátil", description: "USB, tarjeta TF, entrada AUX y puerto Tipo C con cable incluido." },
      { icon: Battery, title: "Batería 500mAh", description: "Autonomía confiable para uso portátil con carga Tipo C." },
    ],
  },
  {
    id: 4,
    name: "Parlante Mio",
    category: "parlantes",
    price: "Consultar",
    code: "MODM-000S",
    kit: "Kit x 100 unidades",
    image: "/images/parlante-bluetooth-mixor-mio-5w-led-mayorista.webp",
    modalImage: "/images/parlante-bluetooth-mixor-mio-modal-5w-led.webp",
    description: "Parlante portátil 3'' con Bluetooth, luces LED y múltiples funciones",
    features: [
      { icon: Volume2, title: "Potencia de 5W", description: "Parlante de 3'' con sonido claro. Alcance Bluetooth: 10m. Medidas: 8.6x8.6x9cm." },
      { icon: Lightbulb, title: "Luz LED Multicolor", description: "Iluminación LED que acompaña tu música con ambiente visual." },
      { icon: Radio, title: "Funciones Múltiples", description: "Radio FM, tarjeta TF, USB y TWS para conectar dos parlantes." },
      { icon: Battery, title: "Batería 800mAh", description: "Hasta 3 horas de duración. Carga Tipo C con cable incluido." },
    ],
  },
  {
    id: 5,
    name: "Parlante Leal",
    category: "parlantes",
    price: "Consultar",
    code: "MODM-007",
    kit: "Kit x 50 unidades",
    image: "/images/parlante-bluetooth-mixor-leal-8w-microfono-mayorista.webp",
    modalImage: "/images/parlante-bluetooth-mixor-leal-modal-8w-microfono.webp",
    description: "Parlante portátil con Bluetooth 2.0, control de voz y iluminación LED",
    features: [
      { icon: Volume2, title: "Potencia de 8W", description: "Respuesta de frecuencia 20Hz-20kHz para sonido nítido. Diseño compacto 10x10x20cm." },
      { icon: Mic, title: "Control de Voz", description: "Micrófono incorporado para llamadas manos libres y comandos de voz." },
      { icon: Lightbulb, title: "Iluminación LED", description: "Luz LED en un solo color que crea atmósfera perfecta en cualquier ambiente." },
      { icon: Battery, title: "Batería 800mAh", description: "2-3 horas de reproducción continua. Soporte para tarjeta TF." },
    ],
  },
  {
    id: 6,
    name: "Parlante Mito",
    category: "parlantes",
    price: "Consultar",
    code: "MODM-000T",
    kit: "Kit x 50 unidades",
    image: "/images/parlante-bluetooth-mixor-mito-8w-tws-mayorista.webp",
    modalImage: "/images/parlante-bluetooth-mixor-mito-modal-8w-tws.webp",
    description: "Parlante portátil 3'' de 8W con perilla de control, Bluetooth y tecnología TWS",
    features: [
      { icon: Settings, title: "Potencia de 8W", description: "Control ágil de volumen con rueda física. Diseño 11x11x6cm con terminación suave." },
      { icon: Wifi, title: "Bluetooth + TWS", description: "Conexión inalámbrica y tecnología TWS para conectar dos parlantes sin cables." },
      { icon: Usb, title: "Múltiples Entradas", description: "Puerto SD/TF y USB para reproducir música desde diversos dispositivos." },
      { icon: Zap, title: "Diseño Premium", description: "Terminación suave al tacto con gomas antideslizantes. Cable USB A - USB C incluido." },
    ],
  },
  {
    id: 7,
    name: "Parlante Noche",
    category: "parlantes",
    price: "Consultar",
    code: "MODM-0029",
    kit: "Kit x 1 unidad",
    image: "/images/parlante-fiesta-mixor-noche-30w-karaoke-mayorista.webp",
    modalImage: "/images/parlante-fiesta-mixor-noche-modal-30w-karaoke.webp",
    description: "Parlante de fiesta 12'' con 30W, micrófono incluido y luces LED para karaoke",
    features: [
      { icon: Volume2, title: "Potencia de 30W", description: "Parlante de 12'' con 220V. Ideal para fiestas, karaoke, interior y aire libre." },
      { icon: Mic, title: "Micrófono Incluido", description: "Viene con micrófono de accesorio para karaoke y presentaciones." },
      { icon: Lightbulb, title: "Luces LED", description: "Iluminación LED integrada que crea ambiente perfecto para fiestas." },
      { icon: Radio, title: "Radio FM + Batería", description: "Sintonizador de radio y batería recargable de 2h de carga para portabilidad." },
    ],
  },
  {
    id: 8,
    name: "Parlante Caos",
    category: "parlantes",
    price: "Consultar",
    code: "MODM-0028",
    kit: "Kit x 1 unidad",
    image: "/images/parlante-fiesta-mixor-caos-30w-rgb-mayorista.webp",
    modalImage: "/images/parlante-fiesta-mixor-caos-modal-30w-rgb.webp",
    description: "Parlante de fiesta 15'' con 30W, karaoke incorporado y luces LED RGB",
    features: [
      { icon: Volume2, title: "Potencia de 30W", description: "Parlante de 15'' con 12V. Perfecto para karaoke, fiestas y eventos." },
      { icon: Mic, title: "Karaoke + Micrófono", description: "Función de karaoke incorporada con micrófono incluido." },
      { icon: Lightbulb, title: "Luces LED RGB", description: "Iluminación LED multicolor en los laterales para ambiente de fiesta." },
      { icon: Radio, title: "Radio FM + Carga Rápida", description: "Sintonizador de radio y batería recargable de 2h de carga." },
    ],
  },
  {
    id: 9,
    name: "Parlante Alma",
    category: "parlantes",
    price: "Consultar",
    code: "MODM-0027",
    kit: "Kit x 8 unidades",
    image: "/images/parlante-fiesta-mixor-alma-20w-doble-microfono-mayorista.webp",
    modalImage: "/images/parlante-fiesta-mixor-alma-modal-20w-doble-microfono.webp",
    description: "Parlante de fiesta 8'' con 20W, karaoke y doble micrófono para eventos",
    features: [
      { icon: Volume2, title: "Potencia de 20W", description: "Parlante de 8'' con 5V. Ideal para karaoke, fiestas interiores y exteriores." },
      { icon: Mic, title: "Doble Micrófono", description: "Incluye micrófono externo y cuenta con micrófono interno para karaoke." },
      { icon: Lightbulb, title: "Luces LED", description: "Iluminación LED integrada con efecto de fiesta para crear ambiente." },
      { icon: Radio, title: "Radio FM + Batería", description: "Sintonizador de radio y batería recargable con carga rápida de 2h." },
    ],
  },
  {
    id: 10,
    name: "Smartwatch Pulso",
    category: "smartwatch",
    price: "Consultar",
    code: "MODM-00GP",
    kit: "Kit x 100 unidades",
    image: "/images/smartwatch-mixor-pulso-pantalla-led-mayorista-argentina.webp",
    modalImage: "/images/smartwatch-mixor-pulso-modal-pantalla-led.webp",
    description: "Smartwatch redondo con pantalla LED 1.52'', dos mallas y batería eficiente",
    features: [
      { icon: Watch, title: "Pantalla LED 1.52''", description: "Interfaz 2.5D con efectos 3D y múltiples estilos de carátulas para imágenes nítidas." },
      { icon: Activity, title: "Tres Anillos de Salud", description: "Monitoreo de frecuencia cardíaca, presión arterial y nivel de oxígeno en sangre en tiempo real." },
      { icon: Battery, title: "Batería Eficiente", description: "200 mAh de bajo consumo con carga inalámbrica rápida y tecnología de carga a cero voltios." },
      { icon: Sparkles, title: "Diseño Premium", description: "Acabado metalizado al vacío. Incluye dos mallas de silicona para mayor versatilidad." },
    ],
  },
  {
    id: 11,
    name: "Smartwatch Momentos",
    category: "smartwatch",
    price: "Consultar",
    code: "MODM-00ED",
    kit: "Kit x 100 unidades",
    image: "/images/smartwatch-mixor-momentos-ecg-bluetooth-mayorista.webp",
    modalImage: "/images/smartwatch-mixor-momentos-modal-ecg-bluetooth.webp",
    description: "Smartwatch cuadrado con monitoreo ECG, llamadas Bluetooth y modos deportivos",
    features: [
      { icon: Heart, title: "Monitoreo ECG + Salud", description: "Tres anillos de salud con monitoreo ECG, frecuencia cardíaca, presión arterial y oxígeno en sangre." },
      { icon: Phone, title: "Llamadas y Música", description: "Atendé llamadas desde tu muñeca y escuchá tu música favorita por Bluetooth." },
      { icon: Activity, title: "Múltiples Modos Deportivos", description: "Seguimiento del sueño, modos deportivos, giro de muñeca y control remoto de cámara." },
      { icon: Sparkles, title: "Notificaciones Inteligentes", description: "Recordatorios de llamadas, SMS, redes sociales, alarma, sedentarismo y eventos importantes." },
    ],
  },
  {
    id: 12,
    name: "TWS Claridad",
    category: "auriculares",
    price: "Consultar",
    code: "MODM-009E",
    kit: "Kit x 100 unidades",
    image: "/images/auriculares-tws-mixor-claridad-pantalla-tactil-mayorista.webp",
    modalImage: "/images/auriculares-tws-mixor-claridad-modal-pantalla-tactil.webp",
    description: "Auriculares TWS con estuche inteligente de pantalla táctil a color y Bluetooth avanzado",
    features: [
      { icon: Sparkles, title: "Pantalla Táctil a Color", description: "Estuche inteligente con pantalla táctil para interacción, control y visualización de batería." },
      { icon: Volume2, title: "Audio Inmersivo", description: "Sonido nítido con graves definidos y micrófono integrado para llamadas cristalinas." },
      { icon: Wifi, title: "Bluetooth Avanzado", description: "Conectividad sin cables ágil y estable con control táctil para gestionar reproducción." },
      { icon: Battery, title: "Diseño Ergonómico", description: "Livianos y cómodos para uso prolongado. Larga duración con estuche de carga incluido." },
    ],
  },
  {
    id: 13,
    name: "Auriculares Fusión",
    category: "auriculares",
    price: "Consultar",
    code: "MODM-008N",
    kit: "Kit x 100 unidades",
    image: "/images/auriculares-inalambricos-mixor-fusion-6hs-mayorista.webp",
    modalImage: "/images/auriculares-inalambricos-mixor-fusion-modal-6hs.webp",
    description: "Auriculares inalámbricos over-ear con 6 horas de autonomía y carga rápida en 1 hora",
    features: [
      { icon: Battery, title: "Autonomía Real 6 Horas", description: "Hasta 6 horas de reproducción continua sin interrupciones y carga flash completa en 1 hora." },
      { icon: Volume2, title: "Diseño Ergonómico", description: "Estructura ligera y cómoda, ideal para usar durante horas sin fatiga." },
      { icon: Phone, title: "Control Manos Libres", description: "Función integrada para contestar llamadas con un solo toque, sin sacar el celular." },
      { icon: Wifi, title: "Conexión Estable BT", description: "Tecnología inalámbrica Bluetooth de largo alcance para conexión estable." },
    ],
  },
  {
    id: 14,
    name: "Auriculares Sensación",
    category: "auriculares",
    price: "Consultar",
    code: "MODM-00B6",
    kit: "Kit x 80 unidades",
    image: "/images/auriculares-inalambricos-mixor-sensacion-6hs-mayorista.webp",
    modalImage: "/images/auriculares-inalambricos-mixor-sensacion-modal-6hs.webp",
    description: "Auriculares inalámbricos over-ear con 6 horas de autonomía y carga rápida en 1 hora",
    features: [
      { icon: Battery, title: "Autonomía Real 6 Horas", description: "Hasta 6 horas de reproducción continua sin interrupciones y carga flash completa en 1 hora." },
      { icon: Volume2, title: "Diseño Ergonómico", description: "Estructura ligera y cómoda, ideal para usar durante horas sin fatiga." },
      { icon: Phone, title: "Control Manos Libres", description: "Función integrada para contestar llamadas con un solo toque, sin sacar el celular." },
      { icon: Wifi, title: "Conexión Estable BT", description: "Tecnología inalámbrica Bluetooth de largo alcance para conexión estable." },
    ],
  },
  {
    id: 15,
    name: "Cable Vinculo",
    category: "cables",
    price: "Consultar",
    code: "MODM-137",
    kit: "Kit x 200 unidades",
    image: "/images/cable-usb-tipo-c-mixor-vinculo-71a-mayorista-argentina.webp",
    modalImage: "/images/cable-usb-tipo-c-mixor-vinculo-modal-71a.webp",
    description: "Cable USB 7.1A de 1 metro con carga y datos rápidos, disponible en variantes TC-TC y TC-IP",
    features: [
      { icon: Zap, title: "Carga Ultrarrápida 7.1A", description: "Potente capacidad de 7.1A para carga rápida sin comprometer la seguridad." },
      { icon: Usb, title: "Tipo-C Universal", description: "Disponible en variantes TC-TC y TC-IP para máxima compatibilidad con todos tus dispositivos." },
      { icon: Sparkles, title: "Datos + Carga", description: "Transferencia eficiente de datos mientras cargas smartphones, tablets y equipos electrónicos." },
      { icon: Shield, title: "Diseño Resistente", description: "Cable de 1 metro con diseño elegante negro, resistente al desgaste diario." },
    ],
  },
  {
    id: 17,
    name: "Cable Impulso",
    category: "cables",
    price: "Consultar",
    code: "MODM-601",
    kit: "Kit x 200 unidades",
    image: "/images/cable-usb-tipo-c-mixor-impulso-carga-rapida-mayorista.webp",
    modalImage: "/images/cable-usb-tipo-c-mixor-impulso-modal-carga-rapida.webp",
    description: "Cable USB a Tipo-C de 7.1A para carga rápida, maximiza el potencial de tu cargador",
    features: [
      { icon: Zap, title: "Carga Rápida 7.1A", description: "Capacidad de 7.1A que maximiza el potencial de cargadores rápidos y super rápidos." },
      { icon: Usb, title: "USB a Tipo-C", description: "Conexión USB estándar a Tipo-C para máxima compatibilidad con dispositivos modernos." },
      { icon: Sparkles, title: "Optimiza tu Cargador", description: "Permite que tu cargador de pared alcance su máxima velocidad de carga sin limitaciones." },
      { icon: Battery, title: "Disponible en 2 Colores", description: "Diseño moderno disponible en negro y blanco/beige con detalles en rojo." },
    ],
  },
  {
    id: 19,
    name: "Cable Vital",
    category: "cables",
    price: "Consultar",
    code: "MODM-136",
    kit: "Kit x 200 unidades",
    image: "/images/cable-usb-reforzado-mixor-vital-54a-cobre-mayorista.webp",
    modalImage: "/images/cable-usb-reforzado-mixor-vital-modal-54a-cobre.webp",
    description: "Cable USB reforzado de 5.4A con doble inyección y hilos de cobre puro, disponible en TC y V8",
    features: [
      { icon: Shield, title: "Doble Inyección Reforzada", description: "Construcción ultra resistente que evita quiebres y prolonga la vida útil del cable." },
      { icon: Zap, title: "Carga Estable 5.4A", description: "Compatible con cargadores de alta potencia para carga rápida y eficiente." },
      { icon: Sparkles, title: "Hilos de Cobre Puro", description: "Mejor conductividad y transferencia de energía para rendimiento óptimo." },
      { icon: Settings, title: "Resistente a Uso Intenso", description: "USB-Tipo C y USB a V8 universal. Resistente a tirones y dobleces, 1 metro ideal." },
    ],
  },
  {
    id: 20,
    name: "Cargador Leyenda",
    category: "cargadores",
    price: "Consultar",
    code: "MODM-510",
    kit: "Kit x 200 unidades",
    image: "/images/cargador-pd-65w-mixor-leyenda-usb-c-mayorista.webp",
    modalImage: "/images/cargador-pd-65w-mixor-leyenda-modal-usb-c.webp",
    description: "Cargador PD de 65W con carga rápida y puerto USB-C",
    features: [
      { icon: Zap, title: "Carga Rápida 65W", description: "Potencia de 65W máxima con salida de 9VDC y 5.1A para carga ultrarrápida." },
      { icon: Sparkles, title: "Entrada Universal", description: "Tensión de entrada AC 100-220V - 50/60Hz compatible con todo el mundo." },
      { icon: Battery, title: "Puerto USB-C PD", description: "Tecnología Power Delivery para cargar notebooks, tablets y smartphones." },
      { icon: Settings, title: "Material Resistente", description: "Construcción en ABS de alta calidad para mayor durabilidad y seguridad." },
    ],
  },
  {
    id: 21,
    name: "Cargador Somos",
    category: "cargadores",
    price: "Consultar",
    code: "MODM-017",
    kit: "Kit x 200 unidades",
    image: "/images/cargador-rapido-mixor-somos-19w-cable-v8-mayorista.webp",
    modalImage: "/images/cargador-rapido-mixor-somos-modal-19w-cable-v8.webp",
    description: "Cargador rápido 19W con cable USB a V8 de 1 metro incluido",
    features: [
      { icon: Shield, title: "Protección Integrada", description: "Protección contra sobrecarga para seguridad de tus dispositivos." },
      { icon: Zap, title: "Carga Rápida 3.8A", description: "Salida de 5Vcc, 3.8A para 19W de potencia de carga rápida." },
      { icon: Sparkles, title: "Plug Tipo I Argentina", description: "Cabezal AU / Tipo I compatible con enchufes argentinos. Entrada universal 100-220V." },
      { icon: Usb, title: "Cable USB a V8", description: "Incluye cable USB a V8 de 1 metro para mayor comodidad." },
    ],
  },
  {
    id: 22,
    name: "Cargador Proton",
    category: "cargadores",
    price: "Consultar",
    code: "MODM-043",
    kit: "Kit x 200 unidades",
    image: "/images/cargador-auto-mixor-proton-12v-doble-usb-mayorista.webp",
    modalImage: "/images/cargador-auto-mixor-proton-modal-12v-doble-usb.webp",
    description: "Cargador para auto 12V con doble USB y cable V8 incluido",
    features: [
      { icon: Car, title: "Cargador para Auto", description: "Diseñado específicamente para vehículos con entrada 12V." },
      { icon: Usb, title: "Doble Puerto USB", description: "Dos puertos USB para cargar múltiples dispositivos simultáneamente." },
      { icon: Zap, title: "Carga Rápida", description: "Tecnología de carga rápida para dispositivos móviles." },
      { icon: Sparkles, title: "Cable V8 Incluido", description: "Viene con cable V8 para comenzar a cargar de inmediato." },
    ],
  },
  {
    id: 23,
    name: "Cargador Quiero",
    category: "cargadores",
    price: "Consultar",
    code: "MODM-012",
    kit: "Kit x 200 unidades",
    image: "/images/cargador-pared-mixor-quiero-51a-2usb-tipo-c-mayorista.webp",
    modalImage: "/images/cargador-pared-mixor-quiero-modal-51a-2usb-tipo-c.webp",
    description: "Cargador de pared 5.1A con 2 puertos USB y cable Tipo-C incluido",
    features: [
      { icon: Usb, title: "Doble Puerto USB", description: "2 puertos USB con 4.8A para cargar múltiples dispositivos simultáneamente." },
      { icon: Zap, title: "Carga Rápida 5.1A", description: "Potente salida de 5.1A para carga rápida y eficiente." },
      { icon: Sparkles, title: "Entrada Universal", description: "AC 100-220V / 50-60Hz compatible con cualquier enchufe del mundo." },
      { icon: Battery, title: "Cable Tipo-C Incluido", description: "Incluye cable Tipo-C de 1 metro aproximadamente. Compatible con V8 e IP." },
    ],
  },
  {
    id: 24,
    name: "Cargador Realidad",
    category: "cargadores",
    price: "Consultar",
    code: "MIXOR MOD09",
    kit: "Kit x 200 unidades",
    image: "/images/cargador-220v-mixor-realidad-44a-triple-proteccion-mayorista.webp",
    modalImage: "/images/cargador-220v-mixor-realidad-modal-44a-triple-proteccion.webp",
    description: "Cargador 220V de 4.4A con 2 USB y cable incluido, disponible en 3 variantes",
    features: [
      { icon: Usb, title: "Doble Puerto USB", description: "2 puertos USB de 220V para cargar dos dispositivos simultáneamente." },
      { icon: Zap, title: "Carga Rápida 4.4A", description: "Potente salida de 4.4A para carga rápida y eficiente de tus dispositivos." },
      { icon: Shield, title: "Triple Protección", description: "Protección contra sobrecarga, recalentamiento y cortocircuito para máxima seguridad." },
      { icon: Sparkles, title: "3 Variantes de Cable", description: "Disponible con cable Tipo-C, V8 o IP según tus necesidades." },
    ],
  },
  {
    id: 25,
    name: "Inflador Ruta",
    category: "accesorios",
    price: "Consultar",
    code: "MODM-00EI",
    kit: "Kit x 24 unidades",
    image: "/images/inflador-portatil-mixor-ruta-4000mah-digital-mayorista.webp",
    modalImage: "/images/inflador-portatil-mixor-ruta-modal-4000mah-digital.webp",
    description: "Inflador portátil con medidor de presión digital, batería 4000mAh y 4 picos",
    features: [
      { icon: Gauge, title: "Inflador + Medidor", description: "Función dual de inflado y medición de presión con pantalla digital PSI 150." },
      { icon: Battery, title: "Batería 4000mAh", description: "Gran autonomía con carga Tipo C de 2-3hs. Tiempo de uso completo: 15 min." },
      { icon: Sparkles, title: "4 Picos Incluidos", description: "Incluye 4 picos diferentes para válvulas, manguera de salida y cable USB." },
      { icon: Lightbulb, title: "Funciones Extra", description: "Iluminación, Flash, S.O.S, banco de carga y presión preestablecida." },
    ],
  },
  {
    id: 26,
    name: "Holder Atrae",
    category: "accesorios",
    price: "Consultar",
    code: "MODM-00B5",
    kit: "Kit x 200 unidades",
    image: "/images/soporte-magnetico-mixor-atrae-360-universal-mayorista.webp",
    modalImage: "/images/soporte-magnetico-mixor-atrae-modal-360-universal.webp",
    description: "Soporte magnético versátil con rotación 360° para celulares de 4.7'' a 6.9''",
    features: [
      { icon: Sparkles, title: "Sujeción Magnética", description: "Sujeción ultra potente que mantiene tu celular firme y seguro." },
      { icon: Settings, title: "Rotación 360°", description: "Ajusta el ángulo cómodamente para grabar o usar GPS sin vibraciones." },
      { icon: Phone, title: "Compatibilidad Universal", description: "Funciona con celulares de 4.7'' a 6.9'' para máxima versatilidad." },
      { icon: Car, title: "Uso Versátil", description: "Ideal para auto, oficina, escritorios y creación de contenido. Instagram +1." },
    ],
  },
  {
    id: 27,
    name: "Cargador Nexo",
    category: "accesorios",
    price: "Consultar",
    code: "MODM-300",
    kit: "Kit x 50 unidades",
    image: "/images/cargador-notebook-mixor-nexo-9-pines-mayorista.webp",
    modalImage: "/images/cargador-notebook-mixor-nexo-modal-9-pines.webp",
    description: "Cargador universal de notebook con 9 pines intercambiables y selector de voltaje",
    features: [
      { icon: Laptop, title: "Universal para Notebooks", description: "Cargador universal compatible con la mayoría de marcas de notebooks." },
      { icon: Sparkles, title: "9 Pines Intercambiables", description: "Incluye 9 conectores diferentes para adaptarse a cualquier modelo de notebook." },
      { icon: Usb, title: "Incluye Tipo-C", description: "Nuevo pico Tipo-C incluido para notebooks y dispositivos modernos." },
      { icon: Settings, title: "Selector de Voltaje", description: "Con selector de voltaje ajustable para máxima compatibilidad y seguridad." },
    ],
  },
  // --- Próximamente ---
  { id: 29, name: "Smartwatch Activo", category: "smartwatch", price: "Próximamente", code: "MODM-009F", kit: "Kit x 100 unidades", image: "/images/proximo-lanzamiento-mixor-accesorios-tecnologicos.webp", description: "Próximamente disponible" },
  { id: 30, name: "Cable Eternidad", category: "cables", price: "Próximamente", code: "MODM-00PL", kit: "Kit x 500 unidades", image: "/images/proximo-lanzamiento-mixor-accesorios-tecnologicos.webp", description: "Próximamente disponible" },
  { id: 31, name: "Cable Pleno", category: "cables", price: "Próximamente", code: "MODM-00PM", kit: "Kit x 500 unidades", image: "/images/proximo-lanzamiento-mixor-accesorios-tecnologicos.webp", description: "Próximamente disponible" },
  { id: 32, name: "Cargador Sinergia", category: "cargadores", price: "Próximamente", code: "MODM-00SN", kit: "Kit x 80 unidades", image: "/images/proximo-lanzamiento-mixor-accesorios-tecnologicos.webp", description: "Próximamente disponible" },
  { id: 33, name: "Micrófono Voz", category: "accesorios", price: "Próximamente", code: "MODM-00VO", kit: "Kit x 50 unidades", image: "/images/proximo-lanzamiento-mixor-accesorios-tecnologicos.webp", description: "Próximamente disponible" },
  { id: 34, name: "TWS Sincronia", category: "auriculares", price: "Próximamente", code: "MODM-00SY", kit: "Kit x 100 unidades", image: "/images/proximo-lanzamiento-mixor-accesorios-tecnologicos.webp", description: "Próximamente disponible" },
  {
    id: 35,
    name: "Parlante Recuerdo",
    category: "parlantes",
    price: "Consultar",
    code: "MODM-00EG",
    kit: "Kit x 50 unidades",
    image: "/images/parlante-portatil-mixor-recuerdo-bluetooth-rgb-mayorista.webp",
    modalImage: "/images/parlante-portatil-mixor-recuerdo-modal-bluetooth-rgb.webp",
    description: "Parlante portátil con Bluetooth, luces RGB, TWS y batería de 1200mAh. Diseño resistente con mango ergonómico y soporte integrado.",
    features: [
      { icon: Settings, title: "Diseño Resistente y Práctico", description: "Cuerpo de plástico duradero con malla de hierro frontal, mango ergonómico y soporte integrado para estabilizarlo en cualquier superficie." },
      { icon: Wifi, title: "Conectividad Total", description: "Bluetooth inalámbrico, puerto USB, ranura TF (MicroSD), entrada AUX y sintonizador FM incorporado." },
      { icon: Volume2, title: "Sonido Claro y TWS", description: "Altavoz de 5W (4Ω). Emparejá dos parlantes Recuerdo simultáneamente para sonido estéreo envolvente con tecnología TWS." },
      { icon: Battery, title: "Batería Confiable", description: "Batería de litio recargable integrada de 1200mAh para horas de reproducción continua." },
      { icon: Lightbulb, title: "Ambiente Festivo", description: "Sistema de luces RGB que ilumina tus reuniones y crea la atmósfera perfecta." },
    ],
  },
  { id: 36, name: "Lámpara Motivos", category: "accesorios", price: "Próximamente", code: "MODM-00MO", kit: "Kit x 80 unidades", image: "/images/proximo-lanzamiento-mixor-accesorios-tecnologicos.webp", description: "Próximamente disponible" },
  { id: 37, name: "Reloj Sueño", category: "accesorios", price: "Próximamente", code: "MODM-00SU", kit: "Kit x 100 unidades", image: "/images/proximo-lanzamiento-mixor-accesorios-tecnologicos.webp", description: "Próximamente disponible" },
];

export type Product = typeof products[number];
